//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace YouMed72
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zametka
    {
        public int ID { get; set; }
        public string NAME { get; set; }
        public string DATA { get; set; }
    }
}
